flathub/us.zoom.Zoom

us.zoom.Zoom.appdata.xml
us.zoom.Zoom.json

Bump zoom to latest version from Dec 16 2018
Release notes: https://support.zoom.us/hc/en-us/articles/205759689-New-Updates-for-Linux

Bump zoom to 2.6.149990.1216

---

us.zoom.Zoom.appdata.xml
us.zoom.Zoom.json

[Release Notes](https://support.zoom.us/hc/en-us/articles/205759689-New-Updates-for-Linux)
Features:
- Option to Disable Chat During a Meeting
- Call a CRC device without Starting a Meeting
- Consent to Being Recorded Confirmation
- Automatically Save Whiteboard
- Show Which Participant is Annotating
- Display an Indicator for Audio Watermark
- Support for Logging in to Multiple Devices
- Accessibility Enhancements
- Star Individual Messages
- Star Contacts and Chat Channels
Fixes:
- Resolved an issue where Brasilia’s time zone was displaying incorrectly
- Resolved an issue where Zoom was crashing for some Linux users after
annotating
- Bug Fixes

Update Zoom version to 2.8.183302.0415 (2019-04-15)

---

us.zoom.Zoom.appdata.xml
us.zoom.Zoom.json

Bump zoom to version 2.8.222599.0519
Release notes: https://support.zoom.us/hc/en-us/articles/205759689-New-Updates-for-Linux
Changelog:
- Minor Bug Fixes

Bump zoom to version 2.8.222599.0519

---

us.zoom.Zoom.json

This is consumed by https://github.com/endlessm/flatpak-external-data-checker/.
An update is actually available – merging this PR should cause the checker to send an update to 2.9.265650.0716 in due course.

Add x-checker-data

---

us.zoom.Zoom.appdata.xml
us.zoom.Zoom.json

Supersedes #32; this was generated by https://github.com/endlessm/flatpak-external-data-checker/pull/34 which adds support for updating appdata.

Update zoom.tar.xz to 3.0.285090.0826

---

.gitmodules
us.zoom.Zoom.json

Since freedesktop 19.08 udev in now in Platform.

Remove shared-modules/udev/udev-175.json

---

us.zoom.Zoom.json

This reverts commit 8ae3b6ff85c2fd13c3eebb9c02e742aa9e621298.
The binary of Qt that zoom bundles doesn't provide any kind
of Wayland support, which in combination with the --fallback-x11
permsission breaks completly the application in Wayland sessions
as it restricts the Xorg socket from being available in the sandbox
and thus Qt fails to find a working backend at all.
Close #24

Revert "add wayland socket"

---

us.zoom.Zoom.json

When extracting as root (i.e. when `flatpak` was run with root
privileges), tar defaults to `--same-owner`, which leads to lots
of ownership change errors like:
```
tar: zoom/libquazip.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: zoom/libquazip.so.1: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: zoom/libturbojpeg.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: zoom/dingdong1.pcm: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: zoom/libfaac1.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: zoom/ring.pcm: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
```
This happens because zoom.tar.xz has …

Don't try to preserve zoom.tar.xz content file owners

---

us.zoom.Zoom.json

I am not clear on the details, but I understand that the KStatusNotifier
protocol involves apps owning bus names of the form
org.kde.KStatusNotifier-x-y where x is the application's PID and y is
some application-determined unique identifier. In the case of (the
current version of) Zoom running in (the current version of) this
Flatpak, it ends up wanting to own org.kde.StatusNotifierItem-8-2.
Allow the app to own all names in this namespace, which allows it to
display a tray icon on (at least) a GNOME(ish) desktop with
https://github.com/ubuntu/gnome-shell-extension-appindicator/ installed.
Fixes #144.

Allow owning org.kde.* for tray icon

---

us.zoom.Zoom.desktop

Add StartupWMClass to desktop file to enable adding it to the favourites on the taskbar in Budgie and others.
Previous discussion here: [https://github.com/flathub/us.zoom.Zoom/pull/145](https://github.com/flathub/us.zoom.Zoom/pull/145)

Add StartupWMClass to desktop file.

---

us.zoom.Zoom.json

Hello,
as you may have known, Zoom has had a lot of privacy and security issues in the past.
My friend and I decided to restrict $HOME so we do not risk users' privacy (some examples mentioned in https://github.com/flatpak/flatpak/issues/3637#issuecomment-633774604) and users' security (mentioned in https://github.com/flatpak/flatpak/issues/3637#issue-624448539). We also have not sacrificed convenience.
What we have done:
- removed rw access to $HOME (`--filesystem=home`);
- the only directories that Zoom has permissions to are: `xdg-documents/Zoom:create`, instead of the whole $HOME:rw (`--filesystem=home`).
- all the contents have now moved from `~/.zoom` to `~/.var/app/us.zoom.Zoom/.zoom`.

Harden sandbox; move content from ~/.zoom to ~/.var/app/us.zoom.Zoom/.zoom

---

us.zoom.Zoom.json

Fix https://github.com/flathub/us.zoom.Zoom/issues/204

Add zoomus.conf support

---

us.zoom.Zoom.desktop

In order to avoid some launchers (like Plank) to display a second, less quality icon, the StartupWMClass needs to match the `WM_CLASS` of the window.
Doing `xprop WM_CLASS` and clicking on the opened window, we can see `WM_CLASS` is actually `zoom` instead of `Zoom`.

Update StartupWMClass name

---

zoom.sh

Currently, the [script](https://github.com/flathub/us.zoom.Zoom/blob/f87bc46751831fa57c91bbec0c39fb36e4dbaabc/zoom.sh) only outputs an error in the console, telling you there is an error that `sed -i 's/enableWaylandShare\=false/enableWaylandShare\=true/' ~/.var/app/us.zoom.Zoom/config/zoomus.conf` did not work because `~/.var/app/us.zoom.Zoom/config/zoomus.conf` did not exist. This only occurs the very first time you run Zoom without its `XDG_CONFIG_HOME` directory. The second launch will run the `sed` command successfully. The user only gets notified about this when running on the console: `flatpak run us.zoom.Zoom`.
This MR suggests a better way for this. The script will now run [Zenity](https://en.wikipedia.org/wiki/Zenity), and prompt the user to restart Zoom when they launch Zoom …

Rewrite zoom.sh for Wayland screenshare

---

us.zoom.Zoom.json
zoom-ld.so.conf
zoom-wrapper.sh
zoom.sh

This restores the sandboxing in a way that it actually is sandboxed, using <https://github.com/refi64/zypak>.
There are two hacks here:
1. If we use zypak-wrapper around ZoomLauncher, LD_PRELOAD gets stripped and the sandbox doesn't work. Therefore, /app/extra/zoom/zoom is renamed to zoom.real and replaced with a wrapper that invokes zypak-wrapper.
2. Zypak invokes the sandbox using flatpak sandboxing, so it's not a child process and doesn't inherit LD_LIBRARY_PATH. As a workaround, the necessary paths are hardcoded in /app/etc/ld.so.conf.
Fixes: https://github.com/flathub/us.zoom.Zoom/issues/326
Fixes: https://github.com/flathub/us.zoom.Zoom/issues/327

Restore sandbox using zypak (fixes launching with arguments)

---

zoom.sh

This was working around
https://support.zoom.us/hc/en-us/requests/14652478, which is fixed in
Zoom 5.11.10, which is already packaged here.
Fixes #348

Remove workaround that sets XDG_CURRENT_DESKTOP to gnome

---

us.zoom.Zoom.appdata.xml
us.zoom.Zoom.json

The new version seems to break :(
https://github.com/flathub/us.zoom.Zoom/issues/367
[📦 us.zoom.Zoom ~]$ /app/extra/zoom/zoom.real
/app/extra/zoom/zoom.real: error while loading shared libraries: libQt5QuickWidgets.so.5: cannot open shared object file: No such file or directory [📦 us.zoom.Zoom ~]$ LD_LIBRARY_PATH=/app/extra/zoom/Qt/lib /app/extra/zoom/zoom.real /app/extra/zoom/zoom.real: error while loading shared libraries: libgssapi_krb5.so.2: cannot open shared object file: No such file or directory
This reverts commit c16edf8755ceaa6e8d7859034f5e43546677ba03, reversing changes made to 3759ac7ee02fb8484ec1a014f810b3cb9e914877.

Revert "Merge pull request #365 from flathub/update-606f636"

---

us.zoom.Zoom.appdata.xml
us.zoom.Zoom.json
zoom-ld.so.conf

The new version of zoom bundles more Qt modules, including libQt5Network.so.5
that depends on libgssapi_krb5.so.2.
So include a stripped down version of krb5 for now.
fixes #367, fixes #369. closes #370.

Update to 5.13.5.431, include krb5 as dep for bundled Qt.

---

us.zoom.Zoom.appdata.xml

Closes #425
There are still two other screenshots where the URLs do work, so it didn't seem important to find a replacement for this one.
Hopefully this unblocks updating Zoom (#424).

Remove outdated screenshot URL

---

us.zoom.Zoom.json

The issue is that Anitya stores the `-final` suffix, so `$version` can't be used. But there's also not always a `$patch`, so there would never be PRs for patch updates.
With the HTML data checker this works correctly.
```
INFO    src.manifest: Checking 2 external data items
INFO    src.manifest: Started check [1/2] archive krb5/krb5-1.21.tar.gz (from us.zoom.Zoom.json)
INFO    src.manifest: Skipped check [2/2] archive zoom/zoom.tar.xz (from us.zoom.Zoom.json)
INFO    src.lib.externaldata: Source krb5-1.21.tar.gz: got new version 1.21.2
INFO    src.manifest: Finished check [2/2] archive krb5/krb5-1.21.tar.gz (from us.zoom.Zoom.json)
OUTDATED: krb5-1.21.tar.gz
Has a new version:
URL:       https://kerberos.org/dist/krb5/1.21/krb5-1.21.2.tar.gz
MD5:       97d5f3a48235c53f6d537c877290d2af …
```

Use html for krb5 update check

---

us.zoom.Zoom.appdata.xml
us.zoom.Zoom.json

This was automatically opened as #424, and closed as superseded by newer versions. But so far, every 5.17.* version has crashed on launch.
Maybe this fixes some other issues without introducing the crash. I'll test it when it's built.

Update to version 5.16.10.668

---

us.zoom.Zoom.appdata.xml
us.zoom.Zoom.json

This reverts commit a7c234017e47de4cb39dae7856c98c4f9a50bd7a, reversing changes made to 6241302e0fd0063f88a4ed2d30e70a91ffdbc600.
It seems that the app is crashing so let's revert.
Fixes https://github.com/flathub/us.zoom.Zoom/pull/436
Fixes https://github.com/flathub/us.zoom.Zoom/issues/437

Revert "Merge pull request #436 from flathub/update-ab7c68f"

---

us.zoom.Zoom.json

by using add it as a persistent folder in the sandbox.  This change provides better sandbox for `.zoom` folder: other app with home dir permission will not be able to read this folder.  This change will also avoid polluting the user's home dir with non-standard dir (`.zoom`).

move `.zoom` folder to the app sandbox

---

us.zoom.Zoom.json

Since 6.1, I've been getting messages 'It looks like "ZoomWebviewHost" crashed...", although the functionality I use still works. I finally got round to digging into this, and it looks like zoom's embedded chromium now has a separate executable, so that `ZoomWebviewHost` needs to be wrapped with Zypak instead of the main `zoom` executable.
I'm hoping this will also fix #473.

Wrap ZoomWebviewHost executable with zypak instead of zoom

---

us.zoom.Zoom.json

This reverts commit da31bd7fd7ac90ee16e148c5d7004895ce0bf66d.
New Zoom versions have issue with pipewire >= 1.2, revert back to 23.08 runtime while the issue is not fixed
https://community.zoom.com/t5/Zoom-Meetings/share-screen-linux-wayland-broken/m-p/184687

Revert "Update runtime to 24.08"

---

zoom.sh

This key is not set by current versions of Zoom, and is also not
necessary: screensharing works out of the box on a fresh install of Zoom
with no existing ~/.var/app/us.zoom.Zoom on a Fedora Silverblue GNOME
session.
Fixes https://github.com/flathub/us.zoom.Zoom/issues/490

Remove enableWaylandShare configuration check

---

us.zoom.Zoom.json

As per the latest feedback ([Solved: re: share screen linux wayland broken](https://community.zoom.com/t5/Zoom-Meetings/share-screen-linux-wayland-broken/m-p/184687/page/4)), the issue with pipewire >= 1.2 seems to be fixed in Zoom 6.2.10.
So we can safely update to 24.08 now.

Update runtime to 24.08

---

us.zoom.Zoom.appdata.xml
us.zoom.Zoom.json

Update Zoom to version 6.4.6.1370.
Add org.gnome.settings-daemon.plugins.media-keys schema from gnome-settings-daemon as a dependencies,
else Zoom version 6.4.6.1370 does not start.

Update to 6.4.6.1370, add org.gnome.settings-daemon.plugins.media-keys
